#!/usr/bin/env bash
# Inline styles.css + app.js into a single self-contained index.html, gzip it,
# and copy it to the firmware embed path. No bundler/toolchain required.
set -euo pipefail
cd "$(dirname "$0")"

SRC=src
OUT=dist
EMBED=../src/standalone/web_assets/index.html.gz
CSRC=../src/standalone/web_assets/web_assets.c

mkdir -p "$OUT"

python3 - "$SRC" "$OUT/index.html" <<'PY'
import sys, pathlib
src, out = pathlib.Path(sys.argv[1]), pathlib.Path(sys.argv[2])
html = (src / "index.html").read_text()
css = (src / "styles.css").read_text()
js = (src / "app.js").read_text()
html = html.replace('<link rel="stylesheet" href="styles.css">', f"<style>\n{css}\n</style>")
html = html.replace('<script src="app.js"></script>', f"<script>\n{js}\n</script>")
out.write_text(html)
print(f"inlined -> {out} ({len(html)} bytes)")
PY

gzip -9 -kf "$OUT/index.html"
mkdir -p "$(dirname "$EMBED")"
cp "$OUT/index.html.gz" "$EMBED"

# Emit a plain C byte-array source the firmware compiles directly. This avoids
# relying on PlatformIO/IDF embed-file magic (which proved flaky with our custom
# component CMakeLists). web_server.c references index_html_gz[] + _len.
python3 - "$OUT/index.html.gz" "$CSRC" <<'PY'
import sys, pathlib
data = pathlib.Path(sys.argv[1]).read_bytes()
out = pathlib.Path(sys.argv[2])
lines = ["// Auto-generated by web-lite/build.sh from the lite UI. Do not edit.",
         "#include <stddef.h>", "",
         "const unsigned char index_html_gz[] = {"]
for i in range(0, len(data), 16):
    lines.append("  " + ",".join(f"0x{b:02x}" for b in data[i:i+16]) + ",")
lines += ["};", f"const unsigned int index_html_gz_len = {len(data)};", ""]
out.write_text("\n".join(lines))
print(f"wrote {out} ({len(data)} bytes)")
PY

raw=$(wc -c < "$OUT/index.html")
gz=$(wc -c < "$OUT/index.html.gz")
echo "embedded asset: $EMBED  (${raw} -> ${gz} bytes gzipped)"
