package decode

import (
	"bytes"
	"encoding/hex"
	"testing"
)

// Vector generated by the (separately-tested) Python implementation; confirms
// the Go AES-CCM* + NWK decode produce identical results.
const (
	securedFrameHex = "0802000034121e2a2878563412ddccbbaa004b120000736bafae933410fc0a0286e7391fbb"
	plaintextHex    = "0001060004010105011001"
	keyHex          = "000102030405060708090a0b0c0d0e0f"
)

func TestNWKDecryptRoundtrip(t *testing.T) {
	key, _ := hex.DecodeString(keyHex)
	frame, _ := hex.DecodeString(securedFrameHex)
	plain, _ := hex.DecodeString(plaintextHex)

	// without the key: secure but not decrypted
	if n := DecodeNWK(frame, nil); n == nil || !n.Secure || n.Decrypted {
		t.Fatalf("expected secure+undecrypted, got %+v", n)
	}
	// with the key: decrypts to the known plaintext
	n := DecodeNWK(frame, key)
	if n == nil || !n.Decrypted {
		t.Fatalf("decryption failed: %+v", n)
	}
	if !bytes.Equal(n.Payload, plain) {
		t.Fatalf("payload mismatch: got %x want %x", n.Payload, plain)
	}
	if aps := DecodeAPS(n.Payload); aps == nil || aps.Cluster != 0x0006 {
		t.Fatalf("APS cluster: %+v", aps)
	}
}

func TestDecodeMAC(t *testing.T) {
	mpdu, _ := hex.DecodeString("61882acdab34127856dead0000")
	m := DecodeMAC(mpdu)
	if m.TypeName != "Data" || m.SrcAddr != 0x5678 || m.DstAddr != 0x1234 {
		t.Fatalf("bad mac: %+v", m)
	}
}

func TestDecodeFrameFullStack(t *testing.T) {
	key, _ := hex.DecodeString(keyHex)
	nwk, _ := hex.DecodeString(securedFrameHex)
	// MAC Data header (FCF 0x8861, dst16+src16, pancomp): 61 88 seq dstpan dst16 src16
	hdr := []byte{0x61, 0x88, 0x2a, 0xcd, 0xab, 0x00, 0x00, 0x34, 0x12}
	mpdu := append(append(hdr, nwk...), 0x00, 0x00) // + FCS
	d := DecodeFrame(mpdu, key)
	if d.MAC.TypeName != "Data" || d.NWK == nil || !d.NWK.Decrypted {
		t.Fatalf("stack decode failed: %+v", d)
	}
	if d.APS == nil || d.APS.Cluster != 0x0006 || d.ZCL == nil {
		t.Fatalf("aps/zcl: %+v %+v", d.APS, d.ZCL)
	}
}
